### ISSUE TITLE
Organism.Update: change text fields

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#181]
Make Resistance Property, Genetic Property as Text (resizable edit box)
Make Origin of Strain, Strain Identification as wide as the column (like Strain ID’s )
![image](https://user-images.githubusercontent.com/25675658/229964065-140f014a-5008-48f5-9c51-cc851f7334c4.png)

**Comment by Jo-Zh** [comment]
fixed by add:
 res_property=forms.CharField(widget=forms.Textarea(attrs={'class': 'input-group', 'rows': '3'}), required=False,)
 gen_property=forms.CharField(widget=forms.Textarea(attrs={'class': 'input-group', 'rows': '3'}), required=False,)
 
for field in self.fields.values():
            if isinstance(field.widget, forms.TextInput) or isinstance(field.widget, forms.NumberInput):
                # Add the 'group-input' class to the widget attrs
                attrs = field.widget.attrs
                attrs['class'] = attrs.get('class', '') + 'input-group'
                field.widget.attrs = attrs

in class CreateOrganism_form(ModelForm) in forms.py
